[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
check_format = "fmt --all --check"
check_targets = "check --all-targets --all-features"
check_test = "test --all-features --verbose"
