[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
check = "cargo fmt --all --check && cargo clippy --all-targets --all-features -- -D warnings && cargo check --all-targets --all-features && cargo test --all-features --verbose"
